object Libs {
    const val android_gradlePlugin = "com.android.tools.build:gradle:${Versions.androidGradlePlugin}"
    const val hilt_gradlePlugin  = "com.google.dagger:hilt-android-gradle-plugin:${Versions.hilt}"
    const val kotlin_gradlePlugin  = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlin}"
    const val kotlin_serializationPlugin  = "org.jetbrains.kotlin:kotlin-serialization:${Versions.kotlin}"
    const val kotlin_realmPlugin  = "io.realm.kotlin:gradle-plugin:${Versions.realm}"

    const val androidx_activity_compose = "androidx.activity:activity-compose:${Versions.androidxActivity}"
    const val androidx_appcompat = "androidx.appcompat:appcompat:${Versions.androidxAppCompat}"
    const val androidx_coreKtx = "androidx.core:core-ktx:${Versions.androidxCore}"
    const val androidx_compose_foundation = "androidx.compose.foundation:foundation:${Versions.androidxCompose}"
    const val androidx_compose_foundation_layout = "androidx.compose.foundation:foundation-layout:${Versions.androidxCompose}"
    const val androidx_compose_material = "androidx.compose.material:material:${Versions.androidxCompose}"
    const val androidx_compose_runtime = "androidx.compose.runtime:runtime:${Versions.androidxCompose}"
    const val androidx_compose_ui_tooling = "androidx.compose.ui:ui-tooling:${Versions.androidxCompose}"
    const val androidx_compose_ui_unit = "androidx.compose.ui:ui-unit:${Versions.androidxCompose}"
    const val androidx_compose_ui_tooling_preview = "androidx.compose.ui:ui-tooling-preview:${Versions.androidxCompose}"
    const val androidx_compose_ui_util = "androidx.compose.ui:ui-util:${Versions.androidxCompose}"
    const val androidx_customview_poolingcontainer = "androidx.customview:customview-poolingcontainer:${Versions.androidxCustomView}"
    const val androidx_hilt_navigation_compose = "androidx.hilt:hilt-navigation-compose:${Versions.androidxHiltNavigationCompose}"
    const val androidx_navigation_compose = "androidx.navigation:navigation-compose:${Versions.androidxNavigation}"
    const val androidx_startup = "androidx.startup:startup-runtime:${Versions.androidxStartup}"
    const val coilKt = "io.coil-kt:coil:${Versions.coil}"
    const val coilKt_compose = "io.coil-kt:coil-compose:${Versions.coil}"
    const val hilt_android = "com.google.dagger:hilt-android:${Versions.hilt}"
    const val hilt_compiler = "com.google.dagger:hilt-android-compiler:${Versions.hilt}"
    const val kotlinx_serialization_json = "org.jetbrains.kotlinx:kotlinx-serialization-json:${Versions.kotlinxSerializationJson}"
    const val material = "com.google.android.material:material:${Versions.material}"
    const val okhttp = "com.squareup.okhttp3:okhttp:${Versions.okhttp}"
    const val realm_kotlin_base = "io.realm.kotlin:library-base:${Versions.realm}"
    const val retrofit_core = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    const val retrofit_kotlin_serialization = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:${Versions.retrofitKotlinxSerializationJson}"
}