object Versions {
    const val androidGradlePlugin = "7.2.2"
    const val accompanist = "0.25.0"
    const val androidxActivity = "1.5.1"
    const val androidxAppCompat = "1.4.2"
    const val androidxCore = "1.8.0"
    const val androidxCompose = "1.2.0"
    const val androidxComposeCompiler = "1.2.0"
    const val androidxCustomView = "1.0.0"
    const val androidxHiltNavigationCompose = "1.0.0"
    const val androidxNavigation = "2.5.0"
    const val androidxStartup = "1.1.1"
    const val coil = "2.1.0"
    const val hilt = "2.43.1"
    const val kotlin = "1.7.0"
    const val kotlinxSerializationJson = "1.3.3"
    const val material = "1.6.1"
    const val okhttp = "4.10.0"
    const val realm = "1.0.1"
    const val retrofit = "2.9.0"
    const val retrofitKotlinxSerializationJson = "0.8.0"
}